#!/bin/bash --login
#SBATCH --job-name=GeomBatch
#SBATCH -o output.%J
#SBATCH --error=error.%J
#SBATCH -n 1
#maximum job time in D-HH:MM
#SBATCH -t 48:00:00
#SBATCH --mem-per-cpu=4000
module load hpcw
module load parallel
srun="srun -n1 -N1 --exclusive"
parallel="parallel -N 1 --delay .2 -j $SLURM_NTASKS --joblog parallel_joblog2 --resume"
$parallel "$srun --input=/home/s.engevabj/codes/AerOpt_FoilDesign/AerOpt2D_3.5_181112_1627/Mesh_Data/Geometry{1}/SolverInput{1}.sh /home/s.engevabj/codes/AerOpt_FoilDesign/Executables/Solver_2D" ::: {10..10}
 
mv /home/s.engevabj/codes/AerOpt_FoilDesign/AerOpt2D_3.5_181112_1627/Mesh_Data/Geometry10/Geometry10.rsd /home/s.engevabj/codes/AerOpt_FoilDesign/AerOpt2D_3.5_181112_1627/Solver_Data/Geometry10.rsd
mv /home/s.engevabj/codes/AerOpt_FoilDesign/AerOpt2D_3.5_181112_1627/Mesh_Data/Geometry10/Geometry10.unk /home/s.engevabj/codes/AerOpt_FoilDesign/AerOpt2D_3.5_181112_1627/Solver_Data/Geometry10.unk
